// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;
using System.Text.Json.Serialization;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan AccessToken, corresponding to Stack Exchange API v2's access_token type
    /// http://api.stackexchange.com/docs/types/access-token
    /// </summary>
    public partial class AccessToken : StacManType
    {
        /// <summary>
        /// access_token
        /// </summary>
        [JsonPropertyName("access_token")]
        public string AccessTokenName { get; init; }

        /// <summary>
        /// account_id
        /// </summary>
        [JsonPropertyName("account_id")]
        public int AccountId { get; init; }

        /// <summary>
        /// expires_on_date
        /// </summary>
        [JsonPropertyName("expires_on_date")]
        public DateTime? ExpiresOnDate { get; init; }

        /// <summary>
        /// scope
        /// </summary>
        [JsonPropertyName("scope")]
        public string[] Scope { get; init; }

    }
}
