// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class AccessToken : StacManType
    {
        internal AccessToken(FilterBehavior filterBehavior, Filter filter) : base(filterBehavior, filter, "access_token") { }

        private string _AccessTokenName;
        [Field("access_token")]
        public string AccessTokenName
        {
            get { EnsureFilterContainsField("access_token"); return _AccessTokenName; }
            internal set { _AccessTokenName = value; }
        }

        private int _AccountId;
        [Field("account_id")]
        public int AccountId
        {
            get { EnsureFilterContainsField("account_id"); return _AccountId; }
            internal set { _AccountId = value; }
        }

        private DateTime? _ExpiresOnDate;
        [Field("expires_on_date")]
        public DateTime? ExpiresOnDate
        {
            get { EnsureFilterContainsField("expires_on_date"); return _ExpiresOnDate; }
            internal set { _ExpiresOnDate = value; }
        }

        private string[] _Scope;
        [Field("scope")]
        public string[] Scope
        {
            get { EnsureFilterContainsField("scope"); return _Scope; }
            internal set { _Scope = value; }
        }
    }
}

#pragma warning restore 1591
