// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;
using System.Text.Json.Serialization;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan Answer, corresponding to Stack Exchange API v2's answer type
    /// http://api.stackexchange.com/docs/types/answer
    /// </summary>
    public partial class Answer : StacManType
    {
        /// <summary>
        /// answer_id
        /// </summary>
        [JsonPropertyName("answer_id")]
        public int AnswerId { get; init; }

        /// <summary>
        /// body
        /// </summary>
        [JsonPropertyName("body")]
        public string Body { get; init; }

        /// <summary>
        /// comments
        /// </summary>
        [JsonPropertyName("comments")]
        public Comment[] Comments { get; init; }

        /// <summary>
        /// community_owned_date
        /// </summary>
        [JsonPropertyName("community_owned_date")]
        public DateTime? CommunityOwnedDate { get; init; }

        /// <summary>
        /// creation_date
        /// </summary>
        [JsonPropertyName("creation_date")]
        public DateTime CreationDate { get; init; }

        /// <summary>
        /// down_vote_count
        /// </summary>
        [JsonPropertyName("down_vote_count")]
        public int DownVoteCount { get; init; }

        /// <summary>
        /// is_accepted
        /// </summary>
        [JsonPropertyName("is_accepted")]
        public bool IsAccepted { get; init; }

        /// <summary>
        /// last_activity_date
        /// </summary>
        [JsonPropertyName("last_activity_date")]
        public DateTime LastActivityDate { get; init; }

        /// <summary>
        /// last_edit_date
        /// </summary>
        [JsonPropertyName("last_edit_date")]
        public DateTime? LastEditDate { get; init; }

        /// <summary>
        /// link
        /// </summary>
        [JsonPropertyName("link")]
        public string Link { get; init; }

        /// <summary>
        /// locked_date
        /// </summary>
        [JsonPropertyName("locked_date")]
        public DateTime? LockedDate { get; init; }

        /// <summary>
        /// owner
        /// </summary>
        [JsonPropertyName("owner")]
        public ShallowUser Owner { get; init; }

        /// <summary>
        /// question_id
        /// </summary>
        [JsonPropertyName("question_id")]
        public int QuestionId { get; init; }

        /// <summary>
        /// score
        /// </summary>
        [JsonPropertyName("score")]
        public int Score { get; init; }

        /// <summary>
        /// tags -- introduced in API version 2.1
        /// </summary>
        [JsonPropertyName("tags")]
        public string[] Tags { get; init; }

        /// <summary>
        /// title
        /// </summary>
        [JsonPropertyName("title")]
        public string Title { get; init; }

        /// <summary>
        /// up_vote_count
        /// </summary>
        [JsonPropertyName("up_vote_count")]
        public int UpVoteCount { get; init; }

    }
}
