// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class BadgeCount : StacManType
    {
        internal BadgeCount(FilterBehavior filterBehavior, Filter filter) : base(filterBehavior, filter, "badge_count") { }

        private int _Bronze;
        [Field("bronze")]
        public int Bronze
        {
            get { EnsureFilterContainsField("bronze"); return _Bronze; }
            internal set { _Bronze = value; }
        }

        private int _Gold;
        [Field("gold")]
        public int Gold
        {
            get { EnsureFilterContainsField("gold"); return _Gold; }
            internal set { _Gold = value; }
        }

        private int _Silver;
        [Field("silver")]
        public int Silver
        {
            get { EnsureFilterContainsField("silver"); return _Silver; }
            internal set { _Silver = value; }
        }
    }
}

#pragma warning restore 1591
