// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class Badge : StacManType
    {
        internal Badge(FilterBehavior filterBehavior, Filter filter) : base(filterBehavior, filter, "badge") { }

        private int _AwardCount;
        [Field("award_count")]
        public int AwardCount
        {
            get { EnsureFilterContainsField("award_count"); return _AwardCount; }
            internal set { _AwardCount = value; }
        }

        private int _BadgeId;
        [Field("badge_id")]
        public int BadgeId
        {
            get { EnsureFilterContainsField("badge_id"); return _BadgeId; }
            internal set { _BadgeId = value; }
        }

        private Badges.BadgeType _BadgeType;
        [Field("badge_type")]
        public Badges.BadgeType BadgeType
        {
            get { EnsureFilterContainsField("badge_type"); return _BadgeType; }
            internal set { _BadgeType = value; }
        }

        private string _Description;
        [Field("description")]
        public string Description
        {
            get { EnsureFilterContainsField("description"); return _Description; }
            internal set { _Description = value; }
        }

        private string _Link;
        [Field("link")]
        public string Link
        {
            get { EnsureFilterContainsField("link"); return _Link; }
            internal set { _Link = value; }
        }

        private string _Name;
        [Field("name")]
        public string Name
        {
            get { EnsureFilterContainsField("name"); return _Name; }
            internal set { _Name = value; }
        }

        private Badges.Rank _Rank;
        [Field("rank")]
        public Badges.Rank Rank
        {
            get { EnsureFilterContainsField("rank"); return _Rank; }
            internal set { _Rank = value; }
        }

        private ShallowUser _User;
        [Field("user")]
        public ShallowUser User
        {
            get { EnsureFilterContainsField("user"); return _User; }
            internal set { _User = value; }
        }
    }
}

#pragma warning restore 1591
