// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;
using System.Text.Json.Serialization;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan Badge, corresponding to Stack Exchange API v2's badge type
    /// http://api.stackexchange.com/docs/types/badge
    /// </summary>
    public partial class Badge : StacManType
    {
        /// <summary>
        /// award_count
        /// </summary>
        [JsonPropertyName("award_count")]
        public int AwardCount { get; init; }

        /// <summary>
        /// badge_id
        /// </summary>
        [JsonPropertyName("badge_id")]
        public int BadgeId { get; init; }

        /// <summary>
        /// badge_type
        /// </summary>
        [JsonPropertyName("badge_type")]
        public Badges.BadgeType BadgeType { get; init; }

        /// <summary>
        /// description
        /// </summary>
        [JsonPropertyName("description")]
        public string Description { get; init; }

        /// <summary>
        /// link
        /// </summary>
        [JsonPropertyName("link")]
        public string Link { get; init; }

        /// <summary>
        /// name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; init; }

        /// <summary>
        /// rank
        /// </summary>
        [JsonPropertyName("rank")]
        public Badges.Rank Rank { get; init; }

        /// <summary>
        /// user
        /// </summary>
        [JsonPropertyName("user")]
        public ShallowUser User { get; init; }

    }
}
