// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class BadgeCount : StacManType
    {
        [Field("bronze")]
        public int Bronze { get; internal set; }

        [Field("gold")]
        public int Gold { get; internal set; }

        [Field("silver")]
        public int Silver { get; internal set; }

    }
}

#pragma warning restore 1591
