// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class Comment : StacManType
    {
        internal Comment(FilterBehavior filterBehavior, Filter filter) : base(filterBehavior, filter, "comment") { }

        private string _Body;
        [Field("body")]
        public string Body
        {
            get { EnsureFilterContainsField("body"); return _Body; }
            internal set { _Body = value; }
        }

        private int _CommentId;
        [Field("comment_id")]
        public int CommentId
        {
            get { EnsureFilterContainsField("comment_id"); return _CommentId; }
            internal set { _CommentId = value; }
        }

        private DateTime _CreationDate;
        [Field("creation_date")]
        public DateTime CreationDate
        {
            get { EnsureFilterContainsField("creation_date"); return _CreationDate; }
            internal set { _CreationDate = value; }
        }

        private bool _Edited;
        [Field("edited")]
        public bool Edited
        {
            get { EnsureFilterContainsField("edited"); return _Edited; }
            internal set { _Edited = value; }
        }

        private string _Link;
        [Field("link")]
        public string Link
        {
            get { EnsureFilterContainsField("link"); return _Link; }
            internal set { _Link = value; }
        }

        private ShallowUser _Owner;
        [Field("owner")]
        public ShallowUser Owner
        {
            get { EnsureFilterContainsField("owner"); return _Owner; }
            internal set { _Owner = value; }
        }

        private int _PostId;
        [Field("post_id")]
        public int PostId
        {
            get { EnsureFilterContainsField("post_id"); return _PostId; }
            internal set { _PostId = value; }
        }

        private Posts.PostType _PostType;
        [Field("post_type")]
        public Posts.PostType PostType
        {
            get { EnsureFilterContainsField("post_type"); return _PostType; }
            internal set { _PostType = value; }
        }

        private ShallowUser _ReplyToUser;
        [Field("reply_to_user")]
        public ShallowUser ReplyToUser
        {
            get { EnsureFilterContainsField("reply_to_user"); return _ReplyToUser; }
            internal set { _ReplyToUser = value; }
        }

        private int _Score;
        [Field("score")]
        public int Score
        {
            get { EnsureFilterContainsField("score"); return _Score; }
            internal set { _Score = value; }
        }
    }
}

#pragma warning restore 1591
