// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;
using System.Text.Json.Serialization;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan Comment, corresponding to Stack Exchange API v2's comment type
    /// http://api.stackexchange.com/docs/types/comment
    /// </summary>
    public partial class Comment : StacManType
    {
        /// <summary>
        /// body
        /// </summary>
        [JsonPropertyName("body")]
        public string Body { get; init; }

        /// <summary>
        /// body_markdown -- introduced in API version 2.1
        /// </summary>
        [JsonPropertyName("body_markdown")]
        public string BodyMarkdown { get; init; }

        /// <summary>
        /// comment_id
        /// </summary>
        [JsonPropertyName("comment_id")]
        public int CommentId { get; init; }

        /// <summary>
        /// creation_date
        /// </summary>
        [JsonPropertyName("creation_date")]
        public DateTime CreationDate { get; init; }

        /// <summary>
        /// edited
        /// </summary>
        [JsonPropertyName("edited")]
        public bool Edited { get; init; }

        /// <summary>
        /// link
        /// </summary>
        [JsonPropertyName("link")]
        public string Link { get; init; }

        /// <summary>
        /// owner
        /// </summary>
        [JsonPropertyName("owner")]
        public ShallowUser Owner { get; init; }

        /// <summary>
        /// post_id
        /// </summary>
        [JsonPropertyName("post_id")]
        public int PostId { get; init; }

        /// <summary>
        /// post_type
        /// </summary>
        [JsonPropertyName("post_type")]
        public Posts.PostType PostType { get; init; }

        /// <summary>
        /// reply_to_user
        /// </summary>
        [JsonPropertyName("reply_to_user")]
        public ShallowUser ReplyToUser { get; init; }

        /// <summary>
        /// score
        /// </summary>
        [JsonPropertyName("score")]
        public int Score { get; init; }

    }
}
