// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class Comment : StacManType
    {
        [Field("body")]
        public string Body { get; internal set; }

        [Field("comment_id")]
        public int CommentId { get; internal set; }

        [Field("creation_date")]
        public DateTime CreationDate { get; internal set; }

        [Field("edited")]
        public bool Edited { get; internal set; }

        [Field("link")]
        public string Link { get; internal set; }

        [Field("owner")]
        public ShallowUser Owner { get; internal set; }

        [Field("post_id")]
        public int PostId { get; internal set; }

        [Field("post_type")]
        public Posts.PostType PostType { get; internal set; }

        [Field("reply_to_user")]
        public ShallowUser ReplyToUser { get; internal set; }

        [Field("score")]
        public int Score { get; internal set; }

    }
}

#pragma warning restore 1591
