// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan Error, corresponding to Stack Exchange API v2's error type
    /// http://api.stackexchange.com/docs/types/error
    /// </summary>
    public partial class Error : StacManType
    {
        /// <summary>
        /// description
        /// </summary>
        [Field("description")]
        public string Description { get; internal set; }

        /// <summary>
        /// error_id
        /// </summary>
        [Field("error_id")]
        public int ErrorId { get; internal set; }

        /// <summary>
        /// error_name
        /// </summary>
        [Field("error_name")]
        public string ErrorName { get; internal set; }

    }
}
