// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;
using System.Text.Json.Serialization;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan Event, corresponding to Stack Exchange API v2's event type
    /// http://api.stackexchange.com/docs/types/event
    /// </summary>
    public partial class Event : StacManType
    {
        /// <summary>
        /// creation_date
        /// </summary>
        [JsonPropertyName("creation_date")]
        public DateTime CreationDate { get; init; }

        /// <summary>
        /// event_id
        /// </summary>
        [JsonPropertyName("event_id")]
        public int EventId { get; init; }

        /// <summary>
        /// event_type
        /// </summary>
        [JsonPropertyName("event_type")]
        public Events.EventType EventType { get; init; }

        /// <summary>
        /// excerpt
        /// </summary>
        [JsonPropertyName("excerpt")]
        public string Excerpt { get; init; }

        /// <summary>
        /// link
        /// </summary>
        [JsonPropertyName("link")]
        public string Link { get; init; }

    }
}
