// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class Event : StacManType
    {
        internal Event(FilterBehavior filterBehavior, Filter filter) : base(filterBehavior, filter, "event") { }

        private DateTime _CreationDate;
        [Field("creation_date")]
        public DateTime CreationDate
        {
            get { EnsureFilterContainsField("creation_date"); return _CreationDate; }
            internal set { _CreationDate = value; }
        }

        private int _EventId;
        [Field("event_id")]
        public int EventId
        {
            get { EnsureFilterContainsField("event_id"); return _EventId; }
            internal set { _EventId = value; }
        }

        private Events.EventType _EventType;
        [Field("event_type")]
        public Events.EventType EventType
        {
            get { EnsureFilterContainsField("event_type"); return _EventType; }
            internal set { _EventType = value; }
        }

        private string _Excerpt;
        [Field("excerpt")]
        public string Excerpt
        {
            get { EnsureFilterContainsField("excerpt"); return _Excerpt; }
            internal set { _Excerpt = value; }
        }

        private string _Link;
        [Field("link")]
        public string Link
        {
            get { EnsureFilterContainsField("link"); return _Link; }
            internal set { _Link = value; }
        }
    }
}

#pragma warning restore 1591
