// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class Filter : StacManType
    {
        internal Filter(FilterBehavior filterBehavior, Filter filter) : base(filterBehavior, filter, "filter") { }

        private string _FilterName;
        [Field("filter")]
        public string FilterName
        {
            get { EnsureFilterContainsField("filter"); return _FilterName; }
            internal set { _FilterName = value; }
        }

        private Filters.FilterType _FilterType;
        [Field("filter_type")]
        public Filters.FilterType FilterType
        {
            get { EnsureFilterContainsField("filter_type"); return _FilterType; }
            internal set { _FilterType = value; }
        }

        private string[] _IncludedFields;
        [Field("included_fields")]
        public string[] IncludedFields
        {
            get { EnsureFilterContainsField("included_fields"); return _IncludedFields; }
            internal set { _IncludedFields = value; }
        }
    }
}

#pragma warning restore 1591
