// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;
using System.Text.Json.Serialization;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan Filter, corresponding to Stack Exchange API v2's filter type
    /// http://api.stackexchange.com/docs/types/filter
    /// </summary>
    public partial class Filter : StacManType
    {
        /// <summary>
        /// filter
        /// </summary>
        [JsonPropertyName("filter")]
        public string FilterName { get; init; }

        /// <summary>
        /// filter_type
        /// </summary>
        [JsonPropertyName("filter_type")]
        public Filters.FilterType FilterType { get; init; }

        /// <summary>
        /// included_fields
        /// </summary>
        [JsonPropertyName("included_fields")]
        public string[] IncludedFields { get; init; }

    }
}
