// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;
using System.Text.Json.Serialization;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan InboxItem, corresponding to Stack Exchange API v2's inbox_item type
    /// http://api.stackexchange.com/docs/types/inbox-item
    /// </summary>
    public partial class InboxItem : StacManType
    {
        /// <summary>
        /// answer_id
        /// </summary>
        [JsonPropertyName("answer_id")]
        public int? AnswerId { get; init; }

        /// <summary>
        /// body
        /// </summary>
        [JsonPropertyName("body")]
        public string Body { get; init; }

        /// <summary>
        /// comment_id
        /// </summary>
        [JsonPropertyName("comment_id")]
        public int? CommentId { get; init; }

        /// <summary>
        /// creation_date
        /// </summary>
        [JsonPropertyName("creation_date")]
        public DateTime CreationDate { get; init; }

        /// <summary>
        /// is_unread
        /// </summary>
        [JsonPropertyName("is_unread")]
        public bool IsUnread { get; init; }

        /// <summary>
        /// item_type
        /// </summary>
        [JsonPropertyName("item_type")]
        public InboxItems.ItemType ItemType { get; init; }

        /// <summary>
        /// link
        /// </summary>
        [JsonPropertyName("link")]
        public string Link { get; init; }

        /// <summary>
        /// question_id
        /// </summary>
        [JsonPropertyName("question_id")]
        public int? QuestionId { get; init; }

        /// <summary>
        /// site
        /// </summary>
        [JsonPropertyName("site")]
        public Site Site { get; init; }

        /// <summary>
        /// title
        /// </summary>
        [JsonPropertyName("title")]
        public string Title { get; init; }

    }
}
