// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class Info : StacManType
    {
        [Field("answers_per_minute")]
        public decimal AnswersPerMinute { get; internal set; }

        [Field("api_revision")]
        public string ApiRevision { get; internal set; }

        [Field("badges_per_minute")]
        public decimal BadgesPerMinute { get; internal set; }

        [Field("new_active_users")]
        public int NewActiveUsers { get; internal set; }

        [Field("questions_per_minute")]
        public decimal QuestionsPerMinute { get; internal set; }

        [Field("site")]
        public Site Site { get; internal set; }

        [Field("total_accepted")]
        public int TotalAccepted { get; internal set; }

        [Field("total_answers")]
        public int TotalAnswers { get; internal set; }

        [Field("total_badges")]
        public int TotalBadges { get; internal set; }

        [Field("total_comments")]
        public int TotalComments { get; internal set; }

        [Field("total_questions")]
        public int TotalQuestions { get; internal set; }

        [Field("total_unanswered")]
        public int TotalUnanswered { get; internal set; }

        [Field("total_users")]
        public int TotalUsers { get; internal set; }

        [Field("total_votes")]
        public int TotalVotes { get; internal set; }

    }
}

#pragma warning restore 1591
