// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;
using System.Text.Json.Serialization;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan Info, corresponding to Stack Exchange API v2's info type
    /// http://api.stackexchange.com/docs/types/info
    /// </summary>
    public partial class Info : StacManType
    {
        /// <summary>
        /// answers_per_minute
        /// </summary>
        [JsonPropertyName("answers_per_minute")]
        public decimal AnswersPerMinute { get; init; }

        /// <summary>
        /// api_revision
        /// </summary>
        [JsonPropertyName("api_revision")]
        public string ApiRevision { get; init; }

        /// <summary>
        /// badges_per_minute
        /// </summary>
        [JsonPropertyName("badges_per_minute")]
        public decimal BadgesPerMinute { get; init; }

        /// <summary>
        /// new_active_users
        /// </summary>
        [JsonPropertyName("new_active_users")]
        public int NewActiveUsers { get; init; }

        /// <summary>
        /// questions_per_minute
        /// </summary>
        [JsonPropertyName("questions_per_minute")]
        public decimal QuestionsPerMinute { get; init; }

        /// <summary>
        /// site
        /// </summary>
        [JsonPropertyName("site")]
        public Site Site { get; init; }

        /// <summary>
        /// total_accepted
        /// </summary>
        [JsonPropertyName("total_accepted")]
        public int TotalAccepted { get; init; }

        /// <summary>
        /// total_answers
        /// </summary>
        [JsonPropertyName("total_answers")]
        public int TotalAnswers { get; init; }

        /// <summary>
        /// total_badges
        /// </summary>
        [JsonPropertyName("total_badges")]
        public int TotalBadges { get; init; }

        /// <summary>
        /// total_comments
        /// </summary>
        [JsonPropertyName("total_comments")]
        public int TotalComments { get; init; }

        /// <summary>
        /// total_questions
        /// </summary>
        [JsonPropertyName("total_questions")]
        public int TotalQuestions { get; init; }

        /// <summary>
        /// total_unanswered
        /// </summary>
        [JsonPropertyName("total_unanswered")]
        public int TotalUnanswered { get; init; }

        /// <summary>
        /// total_users
        /// </summary>
        [JsonPropertyName("total_users")]
        public int TotalUsers { get; init; }

        /// <summary>
        /// total_votes
        /// </summary>
        [JsonPropertyName("total_votes")]
        public int TotalVotes { get; init; }

    }
}
