// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;
using System.Text.Json.Serialization;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan MigrationInfo, corresponding to Stack Exchange API v2's migration_info type
    /// http://api.stackexchange.com/docs/types/migration-info
    /// </summary>
    public partial class MigrationInfo : StacManType
    {
        /// <summary>
        /// on_date
        /// </summary>
        [JsonPropertyName("on_date")]
        public DateTime OnDate { get; init; }

        /// <summary>
        /// other_site
        /// </summary>
        [JsonPropertyName("other_site")]
        public Site OtherSite { get; init; }

        /// <summary>
        /// question_id
        /// </summary>
        [JsonPropertyName("question_id")]
        public int QuestionId { get; init; }

    }
}
