// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class NetworkUser : StacManType
    {
        [Field("account_id")]
        public int AccountId { get; internal set; }

        [Field("answer_count")]
        public int AnswerCount { get; internal set; }

        [Field("badge_counts")]
        public BadgeCount BadgeCounts { get; internal set; }

        [Field("creation_date")]
        public DateTime CreationDate { get; internal set; }

        [Field("last_access_date")]
        public DateTime LastAccessDate { get; internal set; }

        [Field("question_count")]
        public int QuestionCount { get; internal set; }

        [Field("reputation")]
        public int Reputation { get; internal set; }

        [Field("site_name")]
        public string SiteName { get; internal set; }

        [Field("site_url")]
        public string SiteUrl { get; internal set; }

        [Field("user_id")]
        public int UserId { get; internal set; }

        [Field("user_type")]
        public Users.UserType UserType { get; internal set; }

    }
}

#pragma warning restore 1591
