// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;
using System.Text.Json.Serialization;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan NetworkUser, corresponding to Stack Exchange API v2's network_user type
    /// http://api.stackexchange.com/docs/types/network-user
    /// </summary>
    public partial class NetworkUser : StacManType
    {
        /// <summary>
        /// account_id
        /// </summary>
        [JsonPropertyName("account_id")]
        public int AccountId { get; init; }

        /// <summary>
        /// answer_count
        /// </summary>
        [JsonPropertyName("answer_count")]
        public int AnswerCount { get; init; }

        /// <summary>
        /// badge_counts
        /// </summary>
        [JsonPropertyName("badge_counts")]
        public BadgeCount BadgeCounts { get; init; }

        /// <summary>
        /// creation_date
        /// </summary>
        [JsonPropertyName("creation_date")]
        public DateTime CreationDate { get; init; }

        /// <summary>
        /// last_access_date
        /// </summary>
        [JsonPropertyName("last_access_date")]
        public DateTime LastAccessDate { get; init; }

        /// <summary>
        /// question_count
        /// </summary>
        [JsonPropertyName("question_count")]
        public int QuestionCount { get; init; }

        /// <summary>
        /// reputation
        /// </summary>
        [JsonPropertyName("reputation")]
        public int Reputation { get; init; }

        /// <summary>
        /// site_name
        /// </summary>
        [JsonPropertyName("site_name")]
        public string SiteName { get; init; }

        /// <summary>
        /// site_url
        /// </summary>
        [JsonPropertyName("site_url")]
        public string SiteUrl { get; init; }

        /// <summary>
        /// user_id
        /// </summary>
        [JsonPropertyName("user_id")]
        public int UserId { get; init; }

        /// <summary>
        /// user_type
        /// </summary>
        [JsonPropertyName("user_type")]
        public Users.UserType UserType { get; init; }

    }
}
