// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan Notification, corresponding to Stack Exchange API v2's notification type
    /// http://api.stackexchange.com/docs/types/notification
    /// </summary>
    public partial class Notification : StacManType
    {
        /// <summary>
        /// body -- introduced in API version 2.1
        /// </summary>
        [Field("body")]
        public string Body { get; internal set; }

        /// <summary>
        /// creation_date -- introduced in API version 2.1
        /// </summary>
        [Field("creation_date")]
        public DateTime CreationDate { get; internal set; }

        /// <summary>
        /// is_unread -- introduced in API version 2.1
        /// </summary>
        [Field("is_unread")]
        public bool IsUnread { get; internal set; }

        /// <summary>
        /// notification_type -- introduced in API version 2.1
        /// </summary>
        [Field("notification_type")]
        public Notifications.NotificationType NotificationType { get; internal set; }

        /// <summary>
        /// post_id -- introduced in API version 2.1
        /// </summary>
        [Field("post_id")]
        public int? PostId { get; internal set; }

        /// <summary>
        /// site -- introduced in API version 2.1
        /// </summary>
        [Field("site")]
        public Site Site { get; internal set; }

    }
}
