// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;
using System.Text.Json.Serialization;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan Notice, corresponding to Stack Exchange API v2's notice type
    /// http://api.stackexchange.com/docs/types/notice
    /// </summary>
    public partial class Notice : StacManType
    {
        /// <summary>
        /// body -- introduced in API version 2.1
        /// </summary>
        [JsonPropertyName("body")]
        public string Body { get; init; }

        /// <summary>
        /// creation_date -- introduced in API version 2.1
        /// </summary>
        [JsonPropertyName("creation_date")]
        public DateTime CreationDate { get; init; }

        /// <summary>
        /// owner_user_id -- introduced in API version 2.1
        /// </summary>
        [JsonPropertyName("owner_user_id")]
        public int OwnerUserId { get; init; }

    }
}
