// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class Post : StacManType
    {
        [Field("body")]
        public string Body { get; internal set; }

        [Field("comments")]
        public Comment[] Comments { get; internal set; }

        [Field("creation_date")]
        public DateTime CreationDate { get; internal set; }

        [Field("down_vote_count")]
        public int DownVoteCount { get; internal set; }

        [Field("last_activity_date")]
        public DateTime LastActivityDate { get; internal set; }

        [Field("last_edit_date")]
        public DateTime? LastEditDate { get; internal set; }

        [Field("owner")]
        public ShallowUser Owner { get; internal set; }

        [Field("post_id")]
        public int PostId { get; internal set; }

        [Field("post_type")]
        public Posts.PostType PostType { get; internal set; }

        [Field("score")]
        public int Score { get; internal set; }

        [Field("up_vote_count")]
        public int UpVoteCount { get; internal set; }

    }
}

#pragma warning restore 1591
