// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;
using System.Text.Json.Serialization;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan Post, corresponding to Stack Exchange API v2's post type
    /// http://api.stackexchange.com/docs/types/post
    /// </summary>
    public partial class Post : StacManType
    {
        /// <summary>
        /// body
        /// </summary>
        [JsonPropertyName("body")]
        public string Body { get; init; }

        /// <summary>
        /// comments
        /// </summary>
        [JsonPropertyName("comments")]
        public Comment[] Comments { get; init; }

        /// <summary>
        /// creation_date
        /// </summary>
        [JsonPropertyName("creation_date")]
        public DateTime CreationDate { get; init; }

        /// <summary>
        /// down_vote_count
        /// </summary>
        [JsonPropertyName("down_vote_count")]
        public int DownVoteCount { get; init; }

        /// <summary>
        /// last_activity_date
        /// </summary>
        [JsonPropertyName("last_activity_date")]
        public DateTime LastActivityDate { get; init; }

        /// <summary>
        /// last_edit_date
        /// </summary>
        [JsonPropertyName("last_edit_date")]
        public DateTime? LastEditDate { get; init; }

        /// <summary>
        /// link -- introduced in API version 2.1
        /// </summary>
        [JsonPropertyName("link")]
        public string Link { get; init; }

        /// <summary>
        /// owner
        /// </summary>
        [JsonPropertyName("owner")]
        public ShallowUser Owner { get; init; }

        /// <summary>
        /// post_id
        /// </summary>
        [JsonPropertyName("post_id")]
        public int PostId { get; init; }

        /// <summary>
        /// post_type
        /// </summary>
        [JsonPropertyName("post_type")]
        public Posts.PostType PostType { get; init; }

        /// <summary>
        /// score
        /// </summary>
        [JsonPropertyName("score")]
        public int Score { get; init; }

        /// <summary>
        /// up_vote_count
        /// </summary>
        [JsonPropertyName("up_vote_count")]
        public int UpVoteCount { get; init; }

    }
}
