// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;
using System.Text.Json.Serialization;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan Question, corresponding to Stack Exchange API v2's question type
    /// http://api.stackexchange.com/docs/types/question
    /// </summary>
    public partial class Question : StacManType
    {
        /// <summary>
        /// accepted_answer_id
        /// </summary>
        [JsonPropertyName("accepted_answer_id")]
        public int? AcceptedAnswerId { get; init; }

        /// <summary>
        /// answer_count
        /// </summary>
        [JsonPropertyName("answer_count")]
        public int AnswerCount { get; init; }

        /// <summary>
        /// answers
        /// </summary>
        [JsonPropertyName("answers")]
        public Answer[] Answers { get; init; }

        /// <summary>
        /// body
        /// </summary>
        [JsonPropertyName("body")]
        public string Body { get; init; }

        /// <summary>
        /// bounty_amount
        /// </summary>
        [JsonPropertyName("bounty_amount")]
        public int? BountyAmount { get; init; }

        /// <summary>
        /// bounty_closes_date
        /// </summary>
        [JsonPropertyName("bounty_closes_date")]
        public DateTime? BountyClosesDate { get; init; }

        /// <summary>
        /// close_vote_count -- introduced in API version 2.1
        /// </summary>
        [JsonPropertyName("close_vote_count")]
        public int CloseVoteCount { get; init; }

        /// <summary>
        /// closed_date
        /// </summary>
        [JsonPropertyName("closed_date")]
        public DateTime? ClosedDate { get; init; }

        /// <summary>
        /// closed_reason
        /// </summary>
        [JsonPropertyName("closed_reason")]
        public string ClosedReason { get; init; }

        /// <summary>
        /// comments
        /// </summary>
        [JsonPropertyName("comments")]
        public Comment[] Comments { get; init; }

        /// <summary>
        /// community_owned_date
        /// </summary>
        [JsonPropertyName("community_owned_date")]
        public DateTime? CommunityOwnedDate { get; init; }

        /// <summary>
        /// creation_date
        /// </summary>
        [JsonPropertyName("creation_date")]
        public DateTime CreationDate { get; init; }

        /// <summary>
        /// delete_vote_count -- introduced in API version 2.1
        /// </summary>
        [JsonPropertyName("delete_vote_count")]
        public int DeleteVoteCount { get; init; }

        /// <summary>
        /// down_vote_count
        /// </summary>
        [JsonPropertyName("down_vote_count")]
        public int DownVoteCount { get; init; }

        /// <summary>
        /// favorite_count
        /// </summary>
        [JsonPropertyName("favorite_count")]
        public int FavoriteCount { get; init; }

        /// <summary>
        /// is_answered
        /// </summary>
        [JsonPropertyName("is_answered")]
        public bool IsAnswered { get; init; }

        /// <summary>
        /// last_activity_date
        /// </summary>
        [JsonPropertyName("last_activity_date")]
        public DateTime LastActivityDate { get; init; }

        /// <summary>
        /// last_edit_date
        /// </summary>
        [JsonPropertyName("last_edit_date")]
        public DateTime? LastEditDate { get; init; }

        /// <summary>
        /// link
        /// </summary>
        [JsonPropertyName("link")]
        public string Link { get; init; }

        /// <summary>
        /// locked_date
        /// </summary>
        [JsonPropertyName("locked_date")]
        public DateTime? LockedDate { get; init; }

        /// <summary>
        /// migrated_from
        /// </summary>
        [JsonPropertyName("migrated_from")]
        public MigrationInfo MigratedFrom { get; init; }

        /// <summary>
        /// migrated_to
        /// </summary>
        [JsonPropertyName("migrated_to")]
        public MigrationInfo MigratedTo { get; init; }

        /// <summary>
        /// notice -- introduced in API version 2.1
        /// </summary>
        [JsonPropertyName("notice")]
        public Notice Notice { get; init; }

        /// <summary>
        /// owner
        /// </summary>
        [JsonPropertyName("owner")]
        public ShallowUser Owner { get; init; }

        /// <summary>
        /// protected_date
        /// </summary>
        [JsonPropertyName("protected_date")]
        public DateTime? ProtectedDate { get; init; }

        /// <summary>
        /// question_id
        /// </summary>
        [JsonPropertyName("question_id")]
        public int QuestionId { get; init; }

        /// <summary>
        /// reopen_vote_count -- introduced in API version 2.1
        /// </summary>
        [JsonPropertyName("reopen_vote_count")]
        public int ReopenVoteCount { get; init; }

        /// <summary>
        /// score
        /// </summary>
        [JsonPropertyName("score")]
        public int Score { get; init; }

        /// <summary>
        /// tags
        /// </summary>
        [JsonPropertyName("tags")]
        public string[] Tags { get; init; }

        /// <summary>
        /// title
        /// </summary>
        [JsonPropertyName("title")]
        public string Title { get; init; }

        /// <summary>
        /// up_vote_count
        /// </summary>
        [JsonPropertyName("up_vote_count")]
        public int UpVoteCount { get; init; }

        /// <summary>
        /// view_count
        /// </summary>
        [JsonPropertyName("view_count")]
        public int ViewCount { get; init; }

    }
}
