// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class QuestionTimeline : StacManType
    {
        internal QuestionTimeline(FilterBehavior filterBehavior, Filter filter) : base(filterBehavior, filter, "question_timeline") { }

        private int? _CommentId;
        [Field("comment_id")]
        public int? CommentId
        {
            get { EnsureFilterContainsField("comment_id"); return _CommentId; }
            internal set { _CommentId = value; }
        }

        private DateTime _CreationDate;
        [Field("creation_date")]
        public DateTime CreationDate
        {
            get { EnsureFilterContainsField("creation_date"); return _CreationDate; }
            internal set { _CreationDate = value; }
        }

        private int? _DownVoteCount;
        [Field("down_vote_count")]
        public int? DownVoteCount
        {
            get { EnsureFilterContainsField("down_vote_count"); return _DownVoteCount; }
            internal set { _DownVoteCount = value; }
        }

        private ShallowUser _Owner;
        [Field("owner")]
        public ShallowUser Owner
        {
            get { EnsureFilterContainsField("owner"); return _Owner; }
            internal set { _Owner = value; }
        }

        private int? _PostId;
        [Field("post_id")]
        public int? PostId
        {
            get { EnsureFilterContainsField("post_id"); return _PostId; }
            internal set { _PostId = value; }
        }

        private int _QuestionId;
        [Field("question_id")]
        public int QuestionId
        {
            get { EnsureFilterContainsField("question_id"); return _QuestionId; }
            internal set { _QuestionId = value; }
        }

        private Guid? _RevisionGuid;
        [Field("revision_guid")]
        public Guid? RevisionGuid
        {
            get { EnsureFilterContainsField("revision_guid"); return _RevisionGuid; }
            internal set { _RevisionGuid = value; }
        }

        private QuestionTimelines.TimelineType _TimelineType;
        [Field("timeline_type")]
        public QuestionTimelines.TimelineType TimelineType
        {
            get { EnsureFilterContainsField("timeline_type"); return _TimelineType; }
            internal set { _TimelineType = value; }
        }

        private int? _UpVoteCount;
        [Field("up_vote_count")]
        public int? UpVoteCount
        {
            get { EnsureFilterContainsField("up_vote_count"); return _UpVoteCount; }
            internal set { _UpVoteCount = value; }
        }

        private ShallowUser _User;
        [Field("user")]
        public ShallowUser User
        {
            get { EnsureFilterContainsField("user"); return _User; }
            internal set { _User = value; }
        }
    }
}

#pragma warning restore 1591
