// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class QuestionTimeline : StacManType
    {
        [Field("comment_id")]
        public int? CommentId { get; internal set; }

        [Field("creation_date")]
        public DateTime CreationDate { get; internal set; }

        [Field("down_vote_count")]
        public int? DownVoteCount { get; internal set; }

        [Field("owner")]
        public ShallowUser Owner { get; internal set; }

        [Field("post_id")]
        public int? PostId { get; internal set; }

        [Field("question_id")]
        public int QuestionId { get; internal set; }

        [Field("revision_guid")]
        public Guid? RevisionGuid { get; internal set; }

        [Field("timeline_type")]
        public QuestionTimelines.TimelineType TimelineType { get; internal set; }

        [Field("up_vote_count")]
        public int? UpVoteCount { get; internal set; }

        [Field("user")]
        public ShallowUser User { get; internal set; }

    }
}

#pragma warning restore 1591
