// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class RelatedSite : StacManType
    {
        [Field("api_site_parameter")]
        public string ApiSiteParameter { get; internal set; }

        [Field("name")]
        public string Name { get; internal set; }

        [Field("relation")]
        public string Relation { get; internal set; }

        [Field("site_url")]
        public string SiteUrl { get; internal set; }

    }
}

#pragma warning restore 1591
