// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class RelatedSite : StacManType
    {
        internal RelatedSite(FilterBehavior filterBehavior, Filter filter) : base(filterBehavior, filter, "related_site") { }

        private string _ApiSiteParameter;
        [Field("api_site_parameter")]
        public string ApiSiteParameter
        {
            get { EnsureFilterContainsField("api_site_parameter"); return _ApiSiteParameter; }
            internal set { _ApiSiteParameter = value; }
        }

        private string _Name;
        [Field("name")]
        public string Name
        {
            get { EnsureFilterContainsField("name"); return _Name; }
            internal set { _Name = value; }
        }

        private string _Relation;
        [Field("relation")]
        public string Relation
        {
            get { EnsureFilterContainsField("relation"); return _Relation; }
            internal set { _Relation = value; }
        }

        private string _SiteUrl;
        [Field("site_url")]
        public string SiteUrl
        {
            get { EnsureFilterContainsField("site_url"); return _SiteUrl; }
            internal set { _SiteUrl = value; }
        }
    }
}

#pragma warning restore 1591
