// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;
using System.Text.Json.Serialization;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan Reputation, corresponding to Stack Exchange API v2's reputation type
    /// http://api.stackexchange.com/docs/types/reputation
    /// </summary>
    public partial class Reputation : StacManType
    {
        /// <summary>
        /// link
        /// </summary>
        [JsonPropertyName("link")]
        public string Link { get; init; }

        /// <summary>
        /// on_date
        /// </summary>
        [JsonPropertyName("on_date")]
        public DateTime OnDate { get; init; }

        /// <summary>
        /// post_id
        /// </summary>
        [JsonPropertyName("post_id")]
        public int PostId { get; init; }

        /// <summary>
        /// post_type
        /// </summary>
        [JsonPropertyName("post_type")]
        public Posts.PostType PostType { get; init; }

        /// <summary>
        /// reputation_change
        /// </summary>
        [JsonPropertyName("reputation_change")]
        public int ReputationChange { get; init; }

        /// <summary>
        /// title
        /// </summary>
        [JsonPropertyName("title")]
        public string Title { get; init; }

        /// <summary>
        /// user_id
        /// </summary>
        [JsonPropertyName("user_id")]
        public int UserId { get; init; }

        /// <summary>
        /// vote_type
        /// </summary>
        [JsonPropertyName("vote_type")]
        public Reputations.VoteType VoteType { get; init; }

    }
}
