// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan ReputationHistory, corresponding to Stack Exchange API v2's reputation_history type
    /// http://api.stackexchange.com/docs/types/reputation-history
    /// </summary>
    public partial class ReputationHistory : StacManType
    {
        /// <summary>
        /// creation_date -- introduced in API version 2.1
        /// </summary>
        [Field("creation_date")]
        public DateTime CreationDate { get; internal set; }

        /// <summary>
        /// post_id -- introduced in API version 2.1
        /// </summary>
        [Field("post_id")]
        public int? PostId { get; internal set; }

        /// <summary>
        /// reputation_change -- introduced in API version 2.1
        /// </summary>
        [Field("reputation_change")]
        public int ReputationChange { get; internal set; }

        /// <summary>
        /// reputation_history_type -- introduced in API version 2.1
        /// </summary>
        [Field("reputation_history_type")]
        public ReputationHistories.ReputationHistoryType ReputationHistoryType { get; internal set; }

        /// <summary>
        /// user_id -- introduced in API version 2.1
        /// </summary>
        [Field("user_id")]
        public int UserId { get; internal set; }

    }
}
