// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class Reputation : StacManType
    {
        internal Reputation(FilterBehavior filterBehavior, Filter filter) : base(filterBehavior, filter, "reputation") { }

        private string _Link;
        [Field("link")]
        public string Link
        {
            get { EnsureFilterContainsField("link"); return _Link; }
            internal set { _Link = value; }
        }

        private DateTime _OnDate;
        [Field("on_date")]
        public DateTime OnDate
        {
            get { EnsureFilterContainsField("on_date"); return _OnDate; }
            internal set { _OnDate = value; }
        }

        private int _PostId;
        [Field("post_id")]
        public int PostId
        {
            get { EnsureFilterContainsField("post_id"); return _PostId; }
            internal set { _PostId = value; }
        }

        private Posts.PostType _PostType;
        [Field("post_type")]
        public Posts.PostType PostType
        {
            get { EnsureFilterContainsField("post_type"); return _PostType; }
            internal set { _PostType = value; }
        }

        private int _ReputationChange;
        [Field("reputation_change")]
        public int ReputationChange
        {
            get { EnsureFilterContainsField("reputation_change"); return _ReputationChange; }
            internal set { _ReputationChange = value; }
        }

        private string _Title;
        [Field("title")]
        public string Title
        {
            get { EnsureFilterContainsField("title"); return _Title; }
            internal set { _Title = value; }
        }

        private int _UserId;
        [Field("user_id")]
        public int UserId
        {
            get { EnsureFilterContainsField("user_id"); return _UserId; }
            internal set { _UserId = value; }
        }

        private Reputations.VoteType _VoteType;
        [Field("vote_type")]
        public Reputations.VoteType VoteType
        {
            get { EnsureFilterContainsField("vote_type"); return _VoteType; }
            internal set { _VoteType = value; }
        }
    }
}

#pragma warning restore 1591
