// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;
using System.Text.Json.Serialization;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan ShallowUser, corresponding to Stack Exchange API v2's shallow_user type
    /// http://api.stackexchange.com/docs/types/shallow-user
    /// </summary>
    public partial class ShallowUser : StacManType
    {
        /// <summary>
        /// accept_rate
        /// </summary>
        [JsonPropertyName("accept_rate")]
        public int? AcceptRate { get; init; }

        /// <summary>
        /// display_name
        /// </summary>
        [JsonPropertyName("display_name")]
        public string DisplayName { get; init; }

        /// <summary>
        /// link
        /// </summary>
        [JsonPropertyName("link")]
        public string Link { get; init; }

        /// <summary>
        /// profile_image
        /// </summary>
        [JsonPropertyName("profile_image")]
        public string ProfileImage { get; init; }

        /// <summary>
        /// reputation
        /// </summary>
        [JsonPropertyName("reputation")]
        public int? Reputation { get; init; }

        /// <summary>
        /// user_id
        /// </summary>
        [JsonPropertyName("user_id")]
        public int? UserId { get; init; }

        /// <summary>
        /// user_type
        /// </summary>
        [JsonPropertyName("user_type")]
        public Users.UserType UserType { get; init; }

    }
}
