// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;
using System.Text.Json.Serialization;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan Site, corresponding to Stack Exchange API v2's site type
    /// http://api.stackexchange.com/docs/types/site
    /// </summary>
    public partial class Site : StacManType
    {
        /// <summary>
        /// aliases
        /// </summary>
        [JsonPropertyName("aliases")]
        public string[] Aliases { get; init; }

        /// <summary>
        /// api_site_parameter
        /// </summary>
        [JsonPropertyName("api_site_parameter")]
        public string ApiSiteParameter { get; init; }

        /// <summary>
        /// audience
        /// </summary>
        [JsonPropertyName("audience")]
        public string Audience { get; init; }

        /// <summary>
        /// closed_beta_date
        /// </summary>
        [JsonPropertyName("closed_beta_date")]
        public DateTime? ClosedBetaDate { get; init; }

        /// <summary>
        /// favicon_url
        /// </summary>
        [JsonPropertyName("favicon_url")]
        public string FaviconUrl { get; init; }

        /// <summary>
        /// high_resolution_icon_url -- introduced in API version 2.1
        /// </summary>
        [JsonPropertyName("high_resolution_icon_url")]
        public string HighResolutionIconUrl { get; init; }

        /// <summary>
        /// icon_url
        /// </summary>
        [JsonPropertyName("icon_url")]
        public string IconUrl { get; init; }

        /// <summary>
        /// launch_date
        /// </summary>
        [JsonPropertyName("launch_date")]
        public DateTime LaunchDate { get; init; }

        /// <summary>
        /// logo_url
        /// </summary>
        [JsonPropertyName("logo_url")]
        public string LogoUrl { get; init; }

        /// <summary>
        /// markdown_extensions
        /// </summary>
        [JsonPropertyName("markdown_extensions")]
        public string[] MarkdownExtensions { get; init; }

        /// <summary>
        /// name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; init; }

        /// <summary>
        /// open_beta_date
        /// </summary>
        [JsonPropertyName("open_beta_date")]
        public DateTime? OpenBetaDate { get; init; }

        /// <summary>
        /// related_sites
        /// </summary>
        [JsonPropertyName("related_sites")]
        public RelatedSite[] RelatedSites { get; init; }

        /// <summary>
        /// site_state
        /// </summary>
        [JsonPropertyName("site_state")]
        public Sites.SiteState SiteState { get; init; }

        /// <summary>
        /// site_type
        /// </summary>
        [JsonPropertyName("site_type")]
        public string SiteType { get; init; }

        /// <summary>
        /// site_url
        /// </summary>
        [JsonPropertyName("site_url")]
        public string SiteUrl { get; init; }

        /// <summary>
        /// styling
        /// </summary>
        [JsonPropertyName("styling")]
        public Styling Styling { get; init; }

        /// <summary>
        /// twitter_account
        /// </summary>
        [JsonPropertyName("twitter_account")]
        public string TwitterAccount { get; init; }

    }
}
