// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class Site : StacManType
    {
        [Field("aliases")]
        public string[] Aliases { get; internal set; }

        [Field("api_site_parameter")]
        public string ApiSiteParameter { get; internal set; }

        [Field("audience")]
        public string Audience { get; internal set; }

        [Field("closed_beta_date")]
        public DateTime? ClosedBetaDate { get; internal set; }

        [Field("favicon_url")]
        public string FaviconUrl { get; internal set; }

        [Field("icon_url")]
        public string IconUrl { get; internal set; }

        [Field("launch_date")]
        public DateTime LaunchDate { get; internal set; }

        [Field("logo_url")]
        public string LogoUrl { get; internal set; }

        [Field("markdown_extensions")]
        public string[] MarkdownExtensions { get; internal set; }

        [Field("name")]
        public string Name { get; internal set; }

        [Field("open_beta_date")]
        public DateTime? OpenBetaDate { get; internal set; }

        [Field("related_sites")]
        public RelatedSite[] RelatedSites { get; internal set; }

        [Field("site_state")]
        public Sites.SiteState SiteState { get; internal set; }

        [Field("site_type")]
        public string SiteType { get; internal set; }

        [Field("site_url")]
        public string SiteUrl { get; internal set; }

        [Field("styling")]
        public Styling Styling { get; internal set; }

        [Field("twitter_account")]
        public string TwitterAccount { get; internal set; }

    }
}

#pragma warning restore 1591
