// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;

namespace StackExchange.StacMan
{
    public partial class StacManClient : INotificationMethods
    {
        /// <summary>
        /// Stack Exchange API Notifications methods
        /// </summary>
        public INotificationMethods Notifications
        {
            get { return this; }
        }

        Task<StacManResponse<Notification>> INotificationMethods.Get(string access_token, string filter, int? page, int? pagesize)
        {
            ValidateString(access_token, "access_token");
            ValidateMinApiVersion("2.1");
            ValidatePaging(page, pagesize);

            var ub = new ApiUrlBuilder(Version, "/notifications", useHttps: true);

            ub.AddParameter("access_token", access_token);
            ub.AddParameter("filter", filter);
            ub.AddParameter("page", page);
            ub.AddParameter("pagesize", pagesize);

            return CreateApiTask<Notification>(ub, HttpMethod.GET, "/notifications");
        }

        Task<StacManResponse<Notification>> INotificationMethods.GetUnread(string access_token, string filter, int? page, int? pagesize)
        {
            ValidateString(access_token, "access_token");
            ValidateMinApiVersion("2.1");
            ValidatePaging(page, pagesize);

            var ub = new ApiUrlBuilder(Version, "/notifications/unread", useHttps: true);

            ub.AddParameter("access_token", access_token);
            ub.AddParameter("filter", filter);
            ub.AddParameter("page", page);
            ub.AddParameter("pagesize", pagesize);

            return CreateApiTask<Notification>(ub, HttpMethod.GET, "/notifications/unread");
        }
    }

    /// <summary>
    /// Stack Exchange API Notifications methods
    /// </summary>
    public interface INotificationMethods
    {
        /// <summary>
        /// Get a user's notifications, outside of the context of a site. [auth required] (API Method: "/notifications") -- introduced in API version 2.1
        /// </summary>
        Task<StacManResponse<Notification>> Get(string access_token, string filter = null, int? page = null, int? pagesize = null);

        /// <summary>
        /// Get a user's unread notifications, outside of the context of a site. [auth required] (API Method: "/notifications/unread") -- introduced in API version 2.1
        /// </summary>
        Task<StacManResponse<Notification>> GetUnread(string access_token, string filter = null, int? page = null, int? pagesize = null);

    }
}
