// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;

namespace StackExchange.StacMan
{
    public partial class StacManClient : IErrorMethods
    {
        /// <summary>
        /// Stack Exchange API Errors methods
        /// </summary>
        public IErrorMethods Errors
        {
            get { return this; }
        }

        Task<StacManResponse<Error>> IErrorMethods.GetAll(string filter, int? page, int? pagesize)
        {
            ValidatePaging(page, pagesize);

            var ub = new ApiUrlBuilder(Version, "/errors", useHttps: false);

            ub.AddParameter("filter", filter);
            ub.AddParameter("page", page);
            ub.AddParameter("pagesize", pagesize);

            return CreateApiTask<Error>(ub, HttpMethod.GET, "/errors");
        }

        Task<StacManResponse<Error>> IErrorMethods.Simulate(int id, string filter)
        {

            var ub = new ApiUrlBuilder(Version, String.Format("/errors/{0}", id), useHttps: false);

            ub.AddParameter("filter", filter);

            return CreateApiTask<Error>(ub, HttpMethod.GET, "/errors/{id}");
        }
    }

    /// <summary>
    /// Stack Exchange API Errors methods
    /// </summary>
    public interface IErrorMethods
    {
        /// <summary>
        /// Get descriptions of all the errors that the API could return. (API Method: "/errors")
        /// </summary>
        Task<StacManResponse<Error>> GetAll(string filter = null, int? page = null, int? pagesize = null);

        /// <summary>
        /// Simulate an API error for testing purposes. (API Method: "/errors/{id}")
        /// </summary>
        Task<StacManResponse<Error>> Simulate(int id, string filter = null);

    }
}
