// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;

namespace StackExchange.StacMan
{
    public partial class StacManClient : IApplicationMethods
    {
        /// <summary>
        /// Stack Exchange API Applications methods
        /// </summary>
        public IApplicationMethods Applications
        {
            get { return this; }
        }

        Task<StacManResponse<AccessToken>> IApplicationMethods.Deauthenticate(IEnumerable<string> accessTokens, string filter, int? page, int? pagesize)
        {
            ValidateEnumerable(accessTokens, "accessTokens");
            ValidatePaging(page, pagesize);

            var ub = new ApiUrlBuilder(Version, String.Format("/apps/{0}/de-authenticate", String.Join(";", accessTokens.Select(HttpUtility.UrlEncode))), useHttps: false);

            ub.AddParameter("filter", filter);
            ub.AddParameter("page", page);
            ub.AddParameter("pagesize", pagesize);

            return CreateApiTask<AccessToken>(ub, HttpMethod.GET, "/apps/{accessTokens}/de-authenticate");
        }
    }

    /// <summary>
    /// Stack Exchange API Applications methods
    /// </summary>
    public interface IApplicationMethods
    {
        /// <summary>
        /// Allows an application to de-authorize itself for a set of users. (API Method: "/apps/{accessTokens}/de-authenticate")
        /// </summary>
        Task<StacManResponse<AccessToken>> Deauthenticate(IEnumerable<string> accessTokens, string filter = null, int? page = null, int? pagesize = null);

    }
}
