// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class Styling : StacManType
    {
        [Field("link_color")]
        public string LinkColor { get; internal set; }

        [Field("tag_background_color")]
        public string TagBackgroundColor { get; internal set; }

        [Field("tag_foreground_color")]
        public string TagForegroundColor { get; internal set; }

    }
}

#pragma warning restore 1591
