// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan Styling, corresponding to Stack Exchange API v2's styling type
    /// http://api.stackexchange.com/docs/types/styling
    /// </summary>
    public partial class Styling : StacManType
    {
        /// <summary>
        /// link_color
        /// </summary>
        [Field("link_color")]
        public string LinkColor { get; internal set; }

        /// <summary>
        /// tag_background_color
        /// </summary>
        [Field("tag_background_color")]
        public string TagBackgroundColor { get; internal set; }

        /// <summary>
        /// tag_foreground_color
        /// </summary>
        [Field("tag_foreground_color")]
        public string TagForegroundColor { get; internal set; }

    }
}
