// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class Styling : StacManType
    {
        internal Styling(FilterBehavior filterBehavior, Filter filter) : base(filterBehavior, filter, "styling") { }

        private string _LinkColor;
        [Field("link_color")]
        public string LinkColor
        {
            get { EnsureFilterContainsField("link_color"); return _LinkColor; }
            internal set { _LinkColor = value; }
        }

        private string _TagBackgroundColor;
        [Field("tag_background_color")]
        public string TagBackgroundColor
        {
            get { EnsureFilterContainsField("tag_background_color"); return _TagBackgroundColor; }
            internal set { _TagBackgroundColor = value; }
        }

        private string _TagForegroundColor;
        [Field("tag_foreground_color")]
        public string TagForegroundColor
        {
            get { EnsureFilterContainsField("tag_foreground_color"); return _TagForegroundColor; }
            internal set { _TagForegroundColor = value; }
        }
    }
}

#pragma warning restore 1591
