// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;
using System.Text.Json.Serialization;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan SuggestedEdit, corresponding to Stack Exchange API v2's suggested_edit type
    /// http://api.stackexchange.com/docs/types/suggested-edit
    /// </summary>
    public partial class SuggestedEdit : StacManType
    {
        /// <summary>
        /// approval_date
        /// </summary>
        [JsonPropertyName("approval_date")]
        public DateTime? ApprovalDate { get; init; }

        /// <summary>
        /// body
        /// </summary>
        [JsonPropertyName("body")]
        public string Body { get; init; }

        /// <summary>
        /// comment
        /// </summary>
        [JsonPropertyName("comment")]
        public string Comment { get; init; }

        /// <summary>
        /// creation_date
        /// </summary>
        [JsonPropertyName("creation_date")]
        public DateTime CreationDate { get; init; }

        /// <summary>
        /// post_id
        /// </summary>
        [JsonPropertyName("post_id")]
        public int PostId { get; init; }

        /// <summary>
        /// post_type
        /// </summary>
        [JsonPropertyName("post_type")]
        public Posts.PostType PostType { get; init; }

        /// <summary>
        /// proposing_user
        /// </summary>
        [JsonPropertyName("proposing_user")]
        public ShallowUser ProposingUser { get; init; }

        /// <summary>
        /// rejection_date
        /// </summary>
        [JsonPropertyName("rejection_date")]
        public DateTime? RejectionDate { get; init; }

        /// <summary>
        /// suggested_edit_id
        /// </summary>
        [JsonPropertyName("suggested_edit_id")]
        public int SuggestedEditId { get; init; }

        /// <summary>
        /// tags
        /// </summary>
        [JsonPropertyName("tags")]
        public string[] Tags { get; init; }

        /// <summary>
        /// title
        /// </summary>
        [JsonPropertyName("title")]
        public string Title { get; init; }

    }
}
