// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class SuggestedEdit : StacManType
    {
        internal SuggestedEdit(FilterBehavior filterBehavior, Filter filter) : base(filterBehavior, filter, "suggested_edit") { }

        private DateTime? _ApprovalDate;
        [Field("approval_date")]
        public DateTime? ApprovalDate
        {
            get { EnsureFilterContainsField("approval_date"); return _ApprovalDate; }
            internal set { _ApprovalDate = value; }
        }

        private string _Body;
        [Field("body")]
        public string Body
        {
            get { EnsureFilterContainsField("body"); return _Body; }
            internal set { _Body = value; }
        }

        private string _Comment;
        [Field("comment")]
        public string Comment
        {
            get { EnsureFilterContainsField("comment"); return _Comment; }
            internal set { _Comment = value; }
        }

        private DateTime _CreationDate;
        [Field("creation_date")]
        public DateTime CreationDate
        {
            get { EnsureFilterContainsField("creation_date"); return _CreationDate; }
            internal set { _CreationDate = value; }
        }

        private int _PostId;
        [Field("post_id")]
        public int PostId
        {
            get { EnsureFilterContainsField("post_id"); return _PostId; }
            internal set { _PostId = value; }
        }

        private Posts.PostType _PostType;
        [Field("post_type")]
        public Posts.PostType PostType
        {
            get { EnsureFilterContainsField("post_type"); return _PostType; }
            internal set { _PostType = value; }
        }

        private ShallowUser _ProposingUser;
        [Field("proposing_user")]
        public ShallowUser ProposingUser
        {
            get { EnsureFilterContainsField("proposing_user"); return _ProposingUser; }
            internal set { _ProposingUser = value; }
        }

        private DateTime? _RejectionDate;
        [Field("rejection_date")]
        public DateTime? RejectionDate
        {
            get { EnsureFilterContainsField("rejection_date"); return _RejectionDate; }
            internal set { _RejectionDate = value; }
        }

        private int _SuggestedEditId;
        [Field("suggested_edit_id")]
        public int SuggestedEditId
        {
            get { EnsureFilterContainsField("suggested_edit_id"); return _SuggestedEditId; }
            internal set { _SuggestedEditId = value; }
        }

        private string[] _Tags;
        [Field("tags")]
        public string[] Tags
        {
            get { EnsureFilterContainsField("tags"); return _Tags; }
            internal set { _Tags = value; }
        }

        private string _Title;
        [Field("title")]
        public string Title
        {
            get { EnsureFilterContainsField("title"); return _Title; }
            internal set { _Title = value; }
        }
    }
}

#pragma warning restore 1591
