// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class Tag : StacManType
    {
        [Field("count")]
        public int Count { get; internal set; }

        [Field("has_synonyms")]
        public bool HasSynonyms { get; internal set; }

        [Field("is_moderator_only")]
        public bool IsModeratorOnly { get; internal set; }

        [Field("is_required")]
        public bool IsRequired { get; internal set; }

        [Field("last_activity_date")]
        public DateTime? LastActivityDate { get; internal set; }

        [Field("name")]
        public string Name { get; internal set; }

        [Field("user_id")]
        public int? UserId { get; internal set; }

    }
}

#pragma warning restore 1591
