// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;
using System.Text.Json.Serialization;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan TagScore, corresponding to Stack Exchange API v2's tag_score type
    /// http://api.stackexchange.com/docs/types/tag-score
    /// </summary>
    public partial class TagScore : StacManType
    {
        /// <summary>
        /// post_count
        /// </summary>
        [JsonPropertyName("post_count")]
        public int PostCount { get; init; }

        /// <summary>
        /// score
        /// </summary>
        [JsonPropertyName("score")]
        public int Score { get; init; }

        /// <summary>
        /// user
        /// </summary>
        [JsonPropertyName("user")]
        public ShallowUser User { get; init; }

    }
}
