// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class TagSynonym : StacManType
    {
        [Field("applied_count")]
        public int AppliedCount { get; internal set; }

        [Field("creation_date")]
        public DateTime CreationDate { get; internal set; }

        [Field("from_tag")]
        public string FromTag { get; internal set; }

        [Field("last_applied_date")]
        public DateTime? LastAppliedDate { get; internal set; }

        [Field("to_tag")]
        public string ToTag { get; internal set; }

    }
}

#pragma warning restore 1591
