// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class TagWiki : StacManType
    {
        internal TagWiki(FilterBehavior filterBehavior, Filter filter) : base(filterBehavior, filter, "tag_wiki") { }

        private string _Body;
        [Field("body")]
        public string Body
        {
            get { EnsureFilterContainsField("body"); return _Body; }
            internal set { _Body = value; }
        }

        private DateTime? _BodyLastEditDate;
        [Field("body_last_edit_date")]
        public DateTime? BodyLastEditDate
        {
            get { EnsureFilterContainsField("body_last_edit_date"); return _BodyLastEditDate; }
            internal set { _BodyLastEditDate = value; }
        }

        private string _Excerpt;
        [Field("excerpt")]
        public string Excerpt
        {
            get { EnsureFilterContainsField("excerpt"); return _Excerpt; }
            internal set { _Excerpt = value; }
        }

        private DateTime? _ExcerptLastEditDate;
        [Field("excerpt_last_edit_date")]
        public DateTime? ExcerptLastEditDate
        {
            get { EnsureFilterContainsField("excerpt_last_edit_date"); return _ExcerptLastEditDate; }
            internal set { _ExcerptLastEditDate = value; }
        }

        private ShallowUser _LastBodyEditor;
        [Field("last_body_editor")]
        public ShallowUser LastBodyEditor
        {
            get { EnsureFilterContainsField("last_body_editor"); return _LastBodyEditor; }
            internal set { _LastBodyEditor = value; }
        }

        private ShallowUser _LastExcerptEditor;
        [Field("last_excerpt_editor")]
        public ShallowUser LastExcerptEditor
        {
            get { EnsureFilterContainsField("last_excerpt_editor"); return _LastExcerptEditor; }
            internal set { _LastExcerptEditor = value; }
        }

        private string _TagName;
        [Field("tag_name")]
        public string TagName
        {
            get { EnsureFilterContainsField("tag_name"); return _TagName; }
            internal set { _TagName = value; }
        }
    }
}

#pragma warning restore 1591
