// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan TopTag, corresponding to Stack Exchange API v2's top_tag type
    /// http://api.stackexchange.com/docs/types/top-tag
    /// </summary>
    public partial class TopTag : StacManType
    {
        /// <summary>
        /// answer_count
        /// </summary>
        [Field("answer_count")]
        public int AnswerCount { get; internal set; }

        /// <summary>
        /// answer_score
        /// </summary>
        [Field("answer_score")]
        public int AnswerScore { get; internal set; }

        /// <summary>
        /// question_count
        /// </summary>
        [Field("question_count")]
        public int QuestionCount { get; internal set; }

        /// <summary>
        /// question_score
        /// </summary>
        [Field("question_score")]
        public int QuestionScore { get; internal set; }

        /// <summary>
        /// tag_name
        /// </summary>
        [Field("tag_name")]
        public string TagName { get; internal set; }

        /// <summary>
        /// user_id -- introduced in API version 2.1
        /// </summary>
        [Field("user_id")]
        public int UserId { get; internal set; }

    }
}
