// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class TopTag : StacManType
    {
        [Field("answer_count")]
        public int AnswerCount { get; internal set; }

        [Field("answer_score")]
        public int AnswerScore { get; internal set; }

        [Field("question_count")]
        public int QuestionCount { get; internal set; }

        [Field("question_score")]
        public int QuestionScore { get; internal set; }

        [Field("tag_name")]
        public string TagName { get; internal set; }

    }
}

#pragma warning restore 1591
