// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class UserTimeline : StacManType
    {
        [Field("badge_id")]
        public int? BadgeId { get; internal set; }

        [Field("comment_id")]
        public int? CommentId { get; internal set; }

        [Field("creation_date")]
        public DateTime CreationDate { get; internal set; }

        [Field("detail")]
        public string Detail { get; internal set; }

        [Field("link")]
        public string Link { get; internal set; }

        [Field("post_id")]
        public int? PostId { get; internal set; }

        [Field("post_type")]
        public Posts.PostType PostType { get; internal set; }

        [Field("suggested_edit_id")]
        public int? SuggestedEditId { get; internal set; }

        [Field("timeline_type")]
        public UserTimelines.TimelineType TimelineType { get; internal set; }

        [Field("title")]
        public string Title { get; internal set; }

        [Field("user_id")]
        public int UserId { get; internal set; }

    }
}

#pragma warning restore 1591
