// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace StackExchange.StacMan
{
    public partial class UserTimeline : StacManType
    {
        internal UserTimeline(FilterBehavior filterBehavior, Filter filter) : base(filterBehavior, filter, "user_timeline") { }

        private int? _BadgeId;
        [Field("badge_id")]
        public int? BadgeId
        {
            get { EnsureFilterContainsField("badge_id"); return _BadgeId; }
            internal set { _BadgeId = value; }
        }

        private int? _CommentId;
        [Field("comment_id")]
        public int? CommentId
        {
            get { EnsureFilterContainsField("comment_id"); return _CommentId; }
            internal set { _CommentId = value; }
        }

        private DateTime _CreationDate;
        [Field("creation_date")]
        public DateTime CreationDate
        {
            get { EnsureFilterContainsField("creation_date"); return _CreationDate; }
            internal set { _CreationDate = value; }
        }

        private string _Detail;
        [Field("detail")]
        public string Detail
        {
            get { EnsureFilterContainsField("detail"); return _Detail; }
            internal set { _Detail = value; }
        }

        private string _Link;
        [Field("link")]
        public string Link
        {
            get { EnsureFilterContainsField("link"); return _Link; }
            internal set { _Link = value; }
        }

        private int? _PostId;
        [Field("post_id")]
        public int? PostId
        {
            get { EnsureFilterContainsField("post_id"); return _PostId; }
            internal set { _PostId = value; }
        }

        private Posts.PostType _PostType;
        [Field("post_type")]
        public Posts.PostType PostType
        {
            get { EnsureFilterContainsField("post_type"); return _PostType; }
            internal set { _PostType = value; }
        }

        private int? _SuggestedEditId;
        [Field("suggested_edit_id")]
        public int? SuggestedEditId
        {
            get { EnsureFilterContainsField("suggested_edit_id"); return _SuggestedEditId; }
            internal set { _SuggestedEditId = value; }
        }

        private UserTimelines.TimelineType _TimelineType;
        [Field("timeline_type")]
        public UserTimelines.TimelineType TimelineType
        {
            get { EnsureFilterContainsField("timeline_type"); return _TimelineType; }
            internal set { _TimelineType = value; }
        }

        private string _Title;
        [Field("title")]
        public string Title
        {
            get { EnsureFilterContainsField("title"); return _Title; }
            internal set { _Title = value; }
        }

        private int _UserId;
        [Field("user_id")]
        public int UserId
        {
            get { EnsureFilterContainsField("user_id"); return _UserId; }
            internal set { _UserId = value; }
        }
    }
}

#pragma warning restore 1591
