// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;
using System.Text.Json.Serialization;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan User, corresponding to Stack Exchange API v2's user type
    /// http://api.stackexchange.com/docs/types/user
    /// </summary>
    public partial class User : StacManType
    {
        /// <summary>
        /// about_me
        /// </summary>
        [JsonPropertyName("about_me")]
        public string AboutMe { get; init; }

        /// <summary>
        /// accept_rate
        /// </summary>
        [JsonPropertyName("accept_rate")]
        public int? AcceptRate { get; init; }

        /// <summary>
        /// account_id
        /// </summary>
        [JsonPropertyName("account_id")]
        public int AccountId { get; init; }

        /// <summary>
        /// age
        /// </summary>
        [JsonPropertyName("age")]
        public int? Age { get; init; }

        /// <summary>
        /// answer_count
        /// </summary>
        [JsonPropertyName("answer_count")]
        public int AnswerCount { get; init; }

        /// <summary>
        /// badge_counts
        /// </summary>
        [JsonPropertyName("badge_counts")]
        public BadgeCount BadgeCounts { get; init; }

        /// <summary>
        /// creation_date
        /// </summary>
        [JsonPropertyName("creation_date")]
        public DateTime CreationDate { get; init; }

        /// <summary>
        /// display_name
        /// </summary>
        [JsonPropertyName("display_name")]
        public string DisplayName { get; init; }

        /// <summary>
        /// down_vote_count
        /// </summary>
        [JsonPropertyName("down_vote_count")]
        public int DownVoteCount { get; init; }

        /// <summary>
        /// is_employee
        /// </summary>
        [JsonPropertyName("is_employee")]
        public bool IsEmployee { get; init; }

        /// <summary>
        /// last_access_date
        /// </summary>
        [JsonPropertyName("last_access_date")]
        public DateTime LastAccessDate { get; init; }

        /// <summary>
        /// last_modified_date
        /// </summary>
        [JsonPropertyName("last_modified_date")]
        public DateTime? LastModifiedDate { get; init; }

        /// <summary>
        /// link
        /// </summary>
        [JsonPropertyName("link")]
        public string Link { get; init; }

        /// <summary>
        /// location
        /// </summary>
        [JsonPropertyName("location")]
        public string Location { get; init; }

        /// <summary>
        /// profile_image
        /// </summary>
        [JsonPropertyName("profile_image")]
        public string ProfileImage { get; init; }

        /// <summary>
        /// question_count
        /// </summary>
        [JsonPropertyName("question_count")]
        public int QuestionCount { get; init; }

        /// <summary>
        /// reputation
        /// </summary>
        [JsonPropertyName("reputation")]
        public int Reputation { get; init; }

        /// <summary>
        /// reputation_change_day
        /// </summary>
        [JsonPropertyName("reputation_change_day")]
        public int ReputationChangeDay { get; init; }

        /// <summary>
        /// reputation_change_month
        /// </summary>
        [JsonPropertyName("reputation_change_month")]
        public int ReputationChangeMonth { get; init; }

        /// <summary>
        /// reputation_change_quarter
        /// </summary>
        [JsonPropertyName("reputation_change_quarter")]
        public int ReputationChangeQuarter { get; init; }

        /// <summary>
        /// reputation_change_week
        /// </summary>
        [JsonPropertyName("reputation_change_week")]
        public int ReputationChangeWeek { get; init; }

        /// <summary>
        /// reputation_change_year
        /// </summary>
        [JsonPropertyName("reputation_change_year")]
        public int ReputationChangeYear { get; init; }

        /// <summary>
        /// timed_penalty_date
        /// </summary>
        [JsonPropertyName("timed_penalty_date")]
        public DateTime? TimedPenaltyDate { get; init; }

        /// <summary>
        /// up_vote_count
        /// </summary>
        [JsonPropertyName("up_vote_count")]
        public int UpVoteCount { get; init; }

        /// <summary>
        /// user_id
        /// </summary>
        [JsonPropertyName("user_id")]
        public int UserId { get; init; }

        /// <summary>
        /// user_type
        /// </summary>
        [JsonPropertyName("user_type")]
        public Users.UserType UserType { get; init; }

        /// <summary>
        /// view_count
        /// </summary>
        [JsonPropertyName("view_count")]
        public int ViewCount { get; init; }

        /// <summary>
        /// website_url
        /// </summary>
        [JsonPropertyName("website_url")]
        public string WebsiteUrl { get; init; }

    }
}
