// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;
using System.Text.Json.Serialization;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan Wrapper, corresponding to Stack Exchange API v2's common wrapper type
    /// http://api.stackexchange.com/docs/wrapper
    /// </summary>
    public partial class Wrapper<T> : StacManType
    {
        /// <summary>
        /// backoff
        /// </summary>
        [JsonPropertyName("backoff")]
        public int? Backoff { get; init; }

        /// <summary>
        /// error_id
        /// </summary>
        [JsonPropertyName("error_id")]
        public int? ErrorId { get; init; }

        /// <summary>
        /// error_message
        /// </summary>
        [JsonPropertyName("error_message")]
        public string ErrorMessage { get; init; }

        /// <summary>
        /// error_name
        /// </summary>
        [JsonPropertyName("error_name")]
        public string ErrorName { get; init; }

        /// <summary>
        /// has_more
        /// </summary>
        [JsonPropertyName("has_more")]
        public bool HasMore { get; init; }

        /// <summary>
        /// items
        /// </summary>
        [JsonPropertyName("items")]
        public T[] Items { get; init; }

        /// <summary>
        /// page
        /// </summary>
        [JsonPropertyName("page")]
        public int Page { get; init; }

        /// <summary>
        /// page_size
        /// </summary>
        [JsonPropertyName("page_size")]
        public int PageSize { get; init; }

        /// <summary>
        /// quota_max
        /// </summary>
        [JsonPropertyName("quota_max")]
        public int QuotaMax { get; init; }

        /// <summary>
        /// quota_remaining
        /// </summary>
        [JsonPropertyName("quota_remaining")]
        public int QuotaRemaining { get; init; }

        /// <summary>
        /// total
        /// </summary>
        [JsonPropertyName("total")]
        public int Total { get; init; }

        /// <summary>
        /// type
        /// </summary>
        [JsonPropertyName("type")]
        public string Type { get; init; }

    }
}
