// <auto-generated>
//     This file was generated by a T4 template.
//     Don't change it directly as your change would get overwritten. Instead, make changes
//     to the .tt file (i.e. the T4 template) and save it to regenerate this file.
// </auto-generated>

using System;

namespace StackExchange.StacMan
{
    /// <summary>
    /// StacMan WritePermission, corresponding to Stack Exchange API v2's write_permission type
    /// http://api.stackexchange.com/docs/types/write-permission
    /// </summary>
    public partial class WritePermission : StacManType
    {
        /// <summary>
        /// can_add -- introduced in API version 2.1
        /// </summary>
        [Field("can_add")]
        public bool CanAdd { get; internal set; }

        /// <summary>
        /// can_delete -- introduced in API version 2.1
        /// </summary>
        [Field("can_delete")]
        public bool CanDelete { get; internal set; }

        /// <summary>
        /// can_edit -- introduced in API version 2.1
        /// </summary>
        [Field("can_edit")]
        public bool CanEdit { get; internal set; }

        /// <summary>
        /// max_daily_actions -- introduced in API version 2.1
        /// </summary>
        [Field("max_daily_actions")]
        public int MaxDailyActions { get; internal set; }

        /// <summary>
        /// min_seconds_between_actions -- introduced in API version 2.1
        /// </summary>
        [Field("min_seconds_between_actions")]
        public int MinSecondsBetweenActions { get; internal set; }

        /// <summary>
        /// object_type -- introduced in API version 2.1
        /// </summary>
        [Field("object_type")]
        public string ObjectType { get; internal set; }

        /// <summary>
        /// user_id -- introduced in API version 2.1
        /// </summary>
        [Field("user_id")]
        public int UserId { get; internal set; }

    }
}
